---
title: "eda"
output: html_document
---

融合三個月資料表
```{r setup, include=FALSE}
if (!require("readxl")) install.packages("readxl")

seven <- read_excel("已標記顧客表 _201907.xlsx")
eight <- read_excel("已標記顧客表 _201908.xlsx")
nine <- read_excel("已標記顧客表 _201909.xlsx")

```

看有沒有遺失值

```{r}
sum(is.na(total))
```
# 有25717筆資料有遺失值



把三個月內，重複出現在各個月的編號merge起來成一筆
只使用出現在最晚時間的資料當作此人的資料，去除較早的資料
```{r}
if (!require("dplyr")) install.packages("dplyr")
total <- semi_join(x = eight, y = seven, by = "編號")
total <- semi_join(x = nine, y = total, by = "編號")
```

#如果要在EDA前就先根據結果標記做區分 在執行這個
```{r}
#只跑其中一行！
total <- total[total$結果標記=="不動作",]
#只跑其中一行！
total <- total[total$結果標記=="流失",]
#只跑其中一行！
total <- total[total$結果標記=="續用",]

```



看性別的分配
```{r}
value_counts <- table(total$性別)
value_counts
```

看年齡的分配
```{r}
value_counts <- table(total$年齡)
value_counts
```
# 四歲就簽約是什麼概念？


看居住地點分布
```{r}
value_counts <- table(total$居住地點)
value_counts
```

#根據地點分類成每個縣市好了

縣市的分配
```{r}

value_counts <- table(total$居住地點)
county <-as.data.frame(value_counts)
total_value = 0
result <- data.frame()
for(i in 1:nrow(county)){
  if(i==1){
    total_value <- total_value + county$Freq[i]
    next
  }
  a <- substr(county$Var1[i-1],1,3)
  b <- substr(county$Var1[i],1,3)
  if(a==b){
    total_value <- total_value + county$Freq[i]

  }else{
    result <- rbind(result, data.frame(x = substr(county$Var1[i-1],1,3), y = total_value))
    total_value <- county$Freq[i]
  }
}
result

```


看購買管道分配
```{r}
value_counts <- table(total$購買管道)
value_counts
```

看商品分配

```{r}
value_counts <- table(total$商品名稱)
value_counts
```

group一下商品

```{r}

value_counts <- table(total$商品名稱)
product <-as.data.frame(value_counts)
total_value = 0
result <- data.frame()
levels = toString(product$Var1)
levels <- sapply(levels, function(x) strsplit(x, ", ")[[1]], USE.NAMES=FALSE)

#把只有Q的商品名前面再加一個Q 方便之後處理
for(i in 1:length(levels)){
  if(nchar(levels[i])!=6){
    levels[i] = paste("Q",levels[i],sep="")
  }
}

product$Var1 <- factor(levels)
#class(product$Var1)

for(i in 1:nrow(product)){
  if(i==1){
    total_value <- total_value + product$Freq[i]
    next
  }
  a <- substr(product$Var1[i-1],1,2)
  b <- substr(product$Var1[i],1,2)
  if(a==b){
    total_value <- total_value + product$Freq[i]

  }else{
    result <- rbind(result, data.frame(x = substr(product$Var1[i-1],1,2), y = total_value))
    total_value <- product$Freq[i]
  }
}
result

```


商品使用費
```{r}
if (!require("Hmisc")) install.packages("Hmisc")
describe(total$商品使用費)

```
#看起來商品使用費可以算是一種level了 只有127種使用費的可能性 

使用天數

```{r}
if (!require("Hmisc")) install.packages("Hmisc")
describe(total$使用天數)

```

綁約剩於天數
```{r}
if (!require("Hmisc")) install.packages("Hmisc")
describe(total$綁約剩餘天數)#負數代表已過天數

```

搭配手機
```{r}
value_counts <- table(total$搭配手機)
value_counts
```
# 我懶得洗這邊資料了 如果之後模型用到在洗

使用手機
```{r}
value_counts <- table(total$使用手機)
value_counts
```
#一樣之後用到在洗


```{r}
#暫時先把無用量處理成0
total$使用上網量[total$使用上網量=="無用量"] <- 0
total$使用上網量 <- as.numeric(total$使用上網量)

if (!require("Hmisc")) install.packages("Hmisc")
describe(total$使用上網量)

```

```{r}
value_counts <- table(total$使用通話量)

#直接把1000以上轉成1500
total$使用通話量[total$使用通話量=="1000以上"] <- 1500
#class(total$使用通話量)

#暫時先把無用量處理成0
total$使用通話量[total$使用通話量=="無用量"] <- 0
total$使用通話量 <- as.numeric(total$使用通話量)

if (!require("Hmisc")) install.packages("Hmisc")
describe(total$使用通話量)

```

```{r}
value_counts <- table(total$繳費情形)
value_counts

```

```{r}
if (!require("Hmisc")) install.packages("Hmisc")
#class(total$留言次數)
total$留言次數 <- as.numeric(total$留言次數)
describe(total$留言次數)

```

```{r}
if (!require("Hmisc")) install.packages("Hmisc")
class(total$同時使用其他商品數量)
total$同時使用其他商品數量 <- as.numeric(total$同時使用其他商品數量)
describe(total$同時使用其他商品數量)
```


```{r}
value_counts <- table(total$結果標記)
value_counts
```
# 結果有至少80%以上是不動作，到底流失率要不要算不動作 = =? 真的無言



儲存成一個檔
```{r}
write.csv(total,'total.csv', row.names = FALSE)
```
